import React from 'react';
// Imports the Authenticator and withAuthenticator components from '@aws-amplify/ui-react'.
// Authenticator is a React component that provides a ready-to-use sign-in and sign-up UI.
// withAuthenticator is a higher-order component that wraps your app component to enforce authentication.
import { Authenticator } from "@aws-amplify/ui-react";

// Imports the default styles for the Amplify UI components. This line ensures that the authenticator looks nice out of the box.
import '@aws-amplify/ui-react/styles.css';

// Imports the awsExports configuration file generated by the Amplify CLI. This file contains the AWS service configurations (like Cognito, AppSync, etc.) specific to your project.

import Fly_Now from "../Pictures/NewBanner.png";
// Configures the Amplify library with the settings from aws-exports.js, which includes all the AWS service configurations for this project.

export function Login(){

    return( 
        <div className='About-Us-Background'>                            {/* parent div */}
            <div>                                                                           
                <img alt="" className="Top-Banner" src={Fly_Now}/>
            </div>

            <div className='About-Us'>                                  { /* Start of banner div*/}
                <h1 className='Word-Color'>
                    About us
                </h1>
                <h2 className='Word-Color'>
                    We are college students at the University of Las Vegas Nevada and our goal is to show cheaper bundle tickets
                </h2>
                <h2 className='Word-Color'>
                    for events including flights and hotels. To access our search engine please login or create an account below.
                </h2>
            
            </div>

            <div
                style={{                                              /* Start of About us div */
                    paddingBottom: '100px'                                                                  
                }}
            >
            <Authenticator>
            </Authenticator>
            </div>

      </div>  /* end of parent div */
    );
}
